name: Test the code

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - uses: actionsx/prettier@v3
        with:
          args: --check .

      - name: Run Go tests
        run: go test -v ./...
